[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "ffmpeg-python",
]
name = "squeeze_vid"
readme = "README.md"
version = "0.1.1"

[project.scripts]
squeeze-vid = "squeeze_vid.app:main"
