name: squeeze-vid
summary: Normalize videos to a minimal, projection-compatible quality.
description: |
      Normalize videos and audio files to a standardized frame rate and quality
      to minimize the file size while maintaining adequate quality for video
      projection.
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  squeeze-vid:
    command: bin/squeeze-vid
    plugs: [home, removable-media]

parts:
  squeeze-vid:
    plugin: python
    source: https://github.com/sil-car/squeeze-vid.git
    build-packages:
      - python3-pip
    override-build: |
      # Install dephell to convert pyproject.toml to setyp.py, which is req'd. by snapcraftctl.
      # https://forum.snapcraft.io/t/building-a-core20-python-snap-using-pyproject-toml/22028/2
      pip3 install --user dephell[full]
      PATH=$HOME/.local/bin:$PATH dephell deps convert --from-path=pyproject.toml --from-format=poetry --to-path=setup.py --to-format=setuppy
      snapcraftctl build
    stage-packages:
      - ffmpeg
