name: squeeze-vid
summary: Normalize videos to a minimal, projection-compatible quality.
description: |
      Normalize videos and audio files to a standardized frame rate and quality
      to minimize the file size while maintaining adequate quality for video
      projection.
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  squeeze-vid:
    command: bin/squeeze-vid
    plugs: [home, removable-media]

parts:
  squeeze-vid:
    plugin: python
    source: https://github.com/sil-car/squeeze-vid.git
    build-packages:
      - python3-pip
    override-build: |
      # https://raw.githubusercontent.com/anonymouse64/streamdeck-ui-snap/master/snap/snapcraft.yaml
      # install pip manually in the build environment so we can install dephell
      # and use it to convert the poetry based pyproject.yoml to setuppy, which
      # snapcraft's python plugin can then build by itself
      # PYTHONHOME=$SNAPCRAFT_PART_INSTALL/usr PYTHONUSERBASE=$SNAPCRAFT_PART_INSTALL $SNAPCRAFT_PART_INSTALL/usr/bin/python3 -m pip install --user pip==20.1
      # PYTHONHOME=$SNAPCRAFT_PART_INSTALL/usr PYTHONUSERBASE=$SNAPCRAFT_PART_INSTALL $SNAPCRAFT_PART_INSTALL/usr/bin/python3 -m pip install --user dephell[full]
      # PYTHONHOME=$SNAPCRAFT_PART_INSTALL/usr PYTHONUSERBASE=$SNAPCRAFT_PART_INSTALL dephell deps convert --from-path pyproject.toml --from-format poetry --to-path setup.py --to-format setuppy
      # https://forum.snapcraft.io/t/building-a-core20-python-snap-using-pyproject-toml/22028/2
      pip3 install --user dephell[full]
      PATH=$HOME/.local/bin:$PATH dephell deps convert --from-path=pyproject.toml --from-format=poetry --to-path=setup.py --to-format=setuppy
      snapcraftctl build
