name: squeeze-vid
summary: Normalize videos to a minimal, projection-compatible quality.
description: |
      Normalize videos and audio files to a standardized frame rate and quality
      to minimize the file size while maintaining adequate quality for video
      projection.
version: git
grade: stable
confinement: devmode
base: core18
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  squeeze-vid:
    command: bin/squeeze-vid
    plugs: [home, removable-media]

parts:
  squeeze-vid:
    plugin: python
    source: https://github.com/sil-car/squeeze-vid.git
    build-packages:
      - python3-pip
    override-build: |
      # Install dephell to convert pyproject.toml to setyp.py, which is req'd. by snapcraftctl.
      # https://forum.snapcraft.io/t/building-a-core20-python-snap-using-pyproject-toml/22028/2
      pip3 install --user dephell[full]
      PATH=$HOME/.local/bin:$PATH dephell deps convert --from-path=pyproject.toml --from-format=poetry --to-path=setup.py --to-format=setuppy
      snapcraftctl build
    # stage-packages:
    #   - ffmpeg

  ffmpeg:
    plugin: nil
    stage-snaps:
      - ffmpeg-integration-gplv3
    stage-packages:
      ### Dynamic-linking safe dependencies
      - libasound2
      - libass9
      - libbluray2
      - libbs2b0
      - libcaca0
      - libdrm2
      - libfontconfig1
      - libfribidi0
      - libgmp10
      - libgraphite2-3
      - libharfbuzz0b
      - libmp3lame0
      - try:
        - libnuma1
      - libogg0
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopus0
      - libslang2
      - libtheora0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvo-amrwbenc0
      - libvorbis0a
      - libvorbisenc2
      - libvpx5
      - libx11-6
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxdmcp6
      - libxext6
      - libxfixes3

      ### GPL dependencies
      - libcdio-cdda2
      - libcdio-paranoia2
      - libcdio17
      - libfftw3-double3
      - librubberband2
      - libsamplerate0
      - libx264-152
      - libx265-146
      - libxvidcore4

      ### GPLv3 dependencies
      - libsmbclient

      ### non-free dependencies
      #- libfdk-aac0
